
--OBJECT LEVEL VALIDATION

SELECT * FROM SYS.DATABASES;  --SHOWS ALL DATABASES

SELECT * FROM SYS.DATABASES
WHERE NAME = 'Emp_Src';

SELECT * FROM SYS.DATABASES
WHERE NAME = 'Map1_Emp_TGT';

--SOURCE TABLE--
USE Emp_Src;
SELECT * FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_NAME = 'EMPLOYEE';

--TARGET TABLE--
use Map1_Emp_TGT;
SELECT * FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_NAME = 'T_EmployeeDetails';


--2. TABLE STRUCTURE/SCHEMA VALIDATION
SP_HELP T_EmployeeDetails;
SP_HELP EMPLOYEE;

--3. COUNT CHECKS
-- STEP 1:

-----------------------------------------------

--DATA VALIDATION TEST QUERY--
--STEP 1 :
--SOURCE MINUS/EXCEPT TARGET

SELECT * FROM Emp_Src.dbo.EMPLOYEE
EXCEPT
SELECT * FROM Map1_emp_TGT.dbo.T_EmployeeDetails;

--STEP 2:
--AND--TARGET MINUS/EXCEPT SOURCE

SELECT * FROM Map1_emp_TGT.dbo.T_EmployeeDetails
EXCEPT
SELECT * FROM Emp_Src.dbo.EMPLOYEE;