
--SQL OPERATORS

SELECT 10 +30;

SELECT 50-30;

SELECT 10*30;

SELECT 30/10;

SELECT 25%2;

USE EXERCISE1;
SELECT * FROM EMPLOYEE;
SELECT SALARY, SALARY +1000 
FROM EXERCISE1.dbo.EMPLOYEE;

SELECT EMPLOYEENO, SALARY*2 FROM EMPLOYEE WHERE EMPLOYEENO = 10;

SELECT EMPNAME,(SALARY+BONUS)  AS ToTal     FROM EMPLOYEE; 

SELECT EMPNAME, SALARY, (SALARY + SALARY * 10/100) AS SalaryIncrement
FROM EMPLOYEE;