
CREATE DATABASE EXERCISE_JOINS;
USE EXERCISE_JOINS;

CREATE TABLE STUDENT (
SNO INT PRIMARY KEY,
SNAME VARCHAR(30),
CLASS VARCHAR(10)); 

CREATE TABLE ADDRESS (
STNO INT,
ADRSS VARCHAR(50)); 

INSERT INTO Student VALUES (1,'A','3rd'); 
INSERT INTO Student VALUES (2,'B','3rd'); 
INSERT INTO Student VALUES (3,'C','3rd'); 
INSERT INTO Student VALUES (4,'D','3rd'); 
INSERT INTO Student VALUES (5,'E','3rd'); 
 
INSERT INTO Address VALUES (1,'Mehdipatnam'); 
INSERT INTO Address VALUES (2,'koti'); 
INSERT INTO Address VALUES (3,'abids'); 
INSERT INTO Address VALUES (6,'Kphb'); 

SELECT * FROM ADDRESS;

SELECT *  FROM STUDENT
AS ST INNER JOIN ADDRESS AS AD      
ON ST.SNO = AD.STNO 

SELECT *  FROM STUDENT
AS ST JOIN ADDRESS AS AD      
ON ST.SNO = AD.STNO 

SELECT *  FROM STUDENT
AS ST, ADDRESS AS AD      
WHERE ST.SNO = AD.STNO 

SELECT * FROM STUDENT AS ST
LEFT JOIN ADDRESS AS AD
		ON ST.SNO =AD.STNO;

SELECT *  FROM STUDENT
AS ST, ADDRESS AS AD      
WHERE ST.SNO = AD.STNO(+); -- THIS WILL WORK IN ORACLE DB2




SELECT *  FROM STUDENT

SELECT * FROM ADDRESS;
 
SELECT * FROM STUDENT AS ST
RIGHT JOIN ADDRESS AS AD
		ON ST.SNO =AD.STNO;



SELECT *  FROM STUDENT

SELECT * FROM ADDRESS;
 
SELECT * FROM STUDENT AS ST
FULL JOIN ADDRESS AS AD
		ON ST.SNO =AD.STNO;

SELECT * FROM STUDENT AS ST
LEFT OUTER JOIN ADDRESS AS AD 
ON ST.SNO = AD.STNO;

SELECT ST.SNAME FROM STUDENT AS ST 
LEFT JOIN ADDRESS AS AD
ON ST.SNO = AD.STNO 
WHERE AD.ADRSS IS NULL;

SELECT ST.SNAME FROM STUDENT AS ST 
LEFT JOIN ADDRESS AS AD
ON ST.SNO = AD.STNO 
WHERE STNO IS NULL;

INSERT INTO ADDRESS VALUES(4, NULL);