USE EXCERCISE_2;
SELECT * FROM TRAIN;

UPDATE TRAIN
SET TRAIN_NAME = 'PUNI EXPRESS'
WHERE TRAIN_NO = 52815;

USE PRACTICE_2;
SELECT * FROM CourseDetails;
INSERT INTO CourseDetails
VALUES(1, 'JAVA', 5000)
INSERT INTO CourseDetails
VALUES(2, 'ETL', 6000)
INSERT INTO CourseDetails
VALUES(3, 'C3', 8000)

UPDATE CourseDetails
SET CourseFee = CourseFee * 2

DELETE FROM TRAIN
WHERE TRAIN_NAME IS NULL;

