SELECT * FROM Emp_Src.DBO.Employee;

SELECT * FROM Map3_Emp_TGT.DBO.Map3_T_Employee;

SELECT EMPLOYEENO,EMPNAME,
CASE GENDER
WHEN 'M' THEN 'Male'
WHEN 'F' THEN 'Female'
END GENDER
, BIRTHPLACE, 
DATENAME(WEEKDAY,[DOB]) AS DayOfBirth, CURRENTLOCATION,
CASE WHEN DESIGNATION = 'PM' THEN 'ProjectManager' 
ELSE DESIGNATION 
END Designation, 
DATEOFJOINING,
(SALARY + BONUS) AS  TotalSalary, DEPTNAME, TOTALEXPERIENCE, MANAGERID
FROM Emp_Src.DBO.Employee
WHERE DeptName IN('IT', 'Finance') AND DateOfLeaving IS NULL
EXCEPT
SELECT * FROM Map3_Emp_TGT.DBO.Map3_T_Employee;

SELECT EMPLOYEENO,EMPNAME,
CASE GENDER
WHEN 'M' THEN 'Male'
WHEN 'F' THEN 'Female'
END GENDER
, BIRTHPLACE, 
DATENAME(WEEKDAY,[DOB]) AS DayOfBirth, CURRENTLOCATION,
CASE WHEN DESIGNATION = 'PM' THEN 'ProjectManager' 
ELSE DESIGNATION 
END Designation, 
DATEOFJOINING,
(SALARY + BONUS) AS  TotalSalary, DEPTNAME, TOTALEXPERIENCE, MANAGERID
FROM Emp_Src.DBO.Employee
WHERE DeptName IN('IT', 'Finance') AND DateOfLeaving IS NULL
AND EmployeeNo = 2;




SELECT * FROM Map3_Emp_TGT.DBO.Map3_T_Employee
WHERE EmployeeNo = 2;



