SELECT * INTO  Map1_emp_TGT.DBO.T_EmployeeDetails from Emp_Src.DBO.Employee;
DROP TABLE  Map1_emp_TGT.DBO.T_EmployeeDetails;


--1) --DATA VALIDATION TEST QUERY
--STEP 1:
--SOURCE MINUS/EXCEPT TARGET
SELECT * from Emp_Src.DBO.Employee
EXCEPT
SELECT * from  Map1_emp_TGT.DBO.T_EmployeeDetails;

--STEP 2:
--AND-- TARGET MINUS/EXCEPT SOURCE
SELECT * from  Map1_emp_TGT.DBO.T_EmployeeDetails
EXCEPT
SELECT * from Emp_Src.DBO.Employee;

--------------------------------------------------------------
SELECT * FROM SYS.DATABASES
WHERE NAME = 'Emp_Src';


use Emp_Src;
SELECT * FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_NAME = 'EMPLOYEE';

SELECT * FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_NAME = 'T_EMPLOYEEDETAILS';


--2 TABLE STRUCTURE/SCHEMA VALIDATIONS
SP_HELP EMPLOYEE;


--3 COUNT CHECK
--STEP 1
SELECT COUNT(EmployeeNo)
FROM Map1_Emp_TGT.dbo.T_EmployeeDetails;

--STEP 2
SELECT COUNT(EmployeeNo)
FROM EMP_Src.dbo.Employee;

--STEP 3 -- COMPARE STEP 1 AND STEP 1 QUERY RESULT . -- NO. OF ROWS SHOULD MATCH

--STEP 4-- CONSTRAINTS CHECK/NULL CHECK/PROFILING CHECK/RECONCILATION CHECK
SELECT * FROM Map1_Emp_TGT.dbo.T_EmployeeDetails
WHERE EmployeeNo IS NULL;
