USE EXERCISE1;

SELECT *  FROM EMPLOYEE     
WHERE SALARY >= 50000 ; 

SELECT EMPNAME,SALARY    FROM EMPLOYEE  
WHERE SALARY <> 25000 ; 
 
SELECT EMPNAME,SALARY,BONUS    FROM EMPLOYEE  
WHERE (SALARY+BONUS) < 50000 ;